### ISSUE TITLE
Build Crashes with 1.6.2 jar

### ISSUE THREAD

**Issue by jonatandahora** [AprilBrother/AprilBeacon-Android-SDK#10]
When building a project using your library with the minSdkVersion set to < 21 i get an error on the shrinkDebugMultiDexComponent task with the following error message

```
java.io.IOException: Can't read [/Users/jonatandahora/dev/kiik/android/app_android/KiiK/build/intermediates/multi-dex/dev/debug/allclasses.jar] (Can't process class [com/aprilbrother/aprilbrothersdk/services/ABeaconUartService$1.class] (Unknown verification type [18] in stack map frame))

```

**Comment by syxdzc** [comment]
You can see this blog http://blog.csdn.net/jiguangcanhen/article/details/41806599

**Comment by syxdzc** [comment]
You can see this blog http://blog.csdn.net/jiguangcanhen/article/details/41806599
