### ISSUE TITLE
build demo project with error: Unknown verification type [16] in stack map frame

### ISSUE THREAD

**Issue by yujiaao** [AprilBrother/AprilBeacon-Android-SDK#11]
Error:Execution failed for task ':app:transformClassesWithMultidexlistForDebug'.
> java.io.IOException: Can't read [/home/xxx/projects/AprilBeaconDemos/app/build/intermediates/transforms/jarMerging/debug/jars/1/1f/combined.jar] (Can't process class [com/aprilbrother/aprilbrothersdk/services/ABeaconUartService$1.class] (Unknown verification type [16] in stack map frame))

**Comment by syxdzc** [comment]
Did you want to proguard the demo?
you can read the readme of the proguard
"if have this question (Can't process class com/aprilbrother/aprilbrothersdk/services/ABeaconUartService$1.class) repalce the proguard.jar"

**Comment by rongxuanhong** [comment]
I try to include the proguard.jar as file under JniLib, but it didn't work. The error remains. so upset!!

**Comment by syxdzc** [comment]
your project is use android studio or eclipse?

**Comment by syxdzc** [comment]
you can try new version ab-sdk-beta1.7.1

**Comment by rongxuanhong** [comment]
First,the version of my android studio is 2.3，and gradle is 3.3,proguard-base is 5.3.2. Second,I follow your tips and change the proguard-base-5.2.jar(ps: I copy the proguard.jar and refactor its name to original name),but when I restart As and try to run this project, Failed again. the message is as follow.

> Error:Execution failed for task ':app:transformClassesWithMultidexlistForDebug'.
> proguard.KeepClassSpecification.<init>(ZZZZZZLproguard/ClassSpecification;)V

I also try to search this problem, and  it said that the version of android studio don't match that of proguad.jar. so I check your demo's gradle version, and I found it is 3.3 ,Thus,I'm confused again,why this happened ?.

**Comment by dhaltmayer** [comment]
We are having this issue also. What was the solution, @syxdzc ?

**Comment by syxdzc** [comment]
if have this question (Can't process class [com/aprilbrother/aprilbrothersdk/services/ABeaconUartService$1.class] (Unknown verification type [18] in stack map frame)) repalce the proguard.jar
ADT: replace sdk/tools/proguard/lib/proguard.jar
android studio: replace android-studio/gradle/m2repository/net/sf/proguard/proguard-base/5.x/proguard-base-5.x.jar
https://github.com/AprilBrother/AprilBeacon-Android-SDK#proguard

**Comment by rongxuanhong** [comment]
not work


------------------ 原始邮件 ------------------
发件人: "syxdzc";<notifications@github.com>;
发送时间: 2017年6月15日(星期四) 上午9:56
收件人: "AprilBrother/AprilBeacon-Android-SDK"<AprilBeacon-Android-SDK@noreply.github.com>; 
抄送: "洪荣宣"<389817374@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [AprilBrother/AprilBeacon-Android-SDK] build demo project witherror: Unknown verification type [16] in stack map frame (#11)




if have this question (Can't process class [com/aprilbrother/aprilbrothersdk/services/ABeaconUartService$1.class] (Unknown verification type [18] in stack map frame)) repalce the proguard.jar
 ADT: replace sdk/tools/proguard/lib/proguard.jar
 android studio: replace android-studio/gradle/m2repository/net/sf/proguard/proguard-base/5.x/proguard-base-5.x.jar
 https://github.com/AprilBrother/AprilBeacon-Android-SDK#proguard

**Comment by saturov** [comment]
@syxdzc we don't think that replacing Proguard with its tweaked overdated version is good to go. We need up-to-date clean Proguard for our project, but using your SDK we loose an ability to use it because of your library internal bug (I suppose so). Why can't you just fix it? Please, it's more than just important.

**Comment by xfeivip** [comment]
我也遇到同样的问题 求解啊
