### ISSUE TITLE
Parcel error caused by wrong Beancon read & write mothods

### ISSUE THREAD

**Issue by yujiaao** [AprilBrother/AprilBeacon-Android-SDK#12]
> FATAL EXCEPTION: main
>                                                                                   Process: com.aprilbrother.aprilbeacondemo, PID: 20345
>                                                                                   java.lang.RuntimeException: Error receiving broadcast Intent { act=com.llzg.beacon.RECEIVER flg=0x10 (has extras) } in com.llzg.activity.MapActivity$BeaconReceiver@425d6290
>                                                                                       at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:778)
>                                                                                       at android.os.Handler.handleCallback(Handler.java:733)
>                                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
>                                                                                       at android.os.Looper.loop(Looper.java:136)
>                                                                                       at android.app.ActivityThread.main(ActivityThread.java:5110)
>                                                                                       at java.lang.reflect.Method.invokeNative(Native Method)
>                                                                                       at java.lang.reflect.Method.invoke(Method.java:515)
>                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
>                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:702)
>                                                                                       at dalvik.system.NativeStart.main(Native Method)
>                                                                                    Caused by: java.lang.RuntimeException: Parcel android.os.Parcel@4255f370: Unmarshalling unknown type code 39 at offset 296
>                                                                                       at android.os.Parcel.readValue(Parcel.java:2080)
>                                                                                       at android.os.Parcel.readListInternal(Parcel.java:2343)
>                                                                                       at android.os.Parcel.readArrayList(Parcel.java:1703)
>                                                                                       at android.os.Parcel.readValue(Parcel.java:2034)
>                                                                                       at android.os.Parcel.readArrayMapInternal(Parcel.java:2314)
>                                                                                       at android.os.Bundle.unparcel(Bundle.java:249)
>                                                                                       at android.os.Bundle.getParcelableArrayList(Bundle.java:1250)
>                                                                                       at android.content.Intent.getParcelableArrayListExtra(Intent.java:4846)

The decompile code shows:

```

    private Beacon(Parcel var1) {
        this.c = null;
        this.e = var1.readString();
        this.f = var1.readString();
        this.g = var1.readString();
        this.h = var1.readInt();
        this.i = var1.readInt();
        this.j = var1.readInt();
        this.k = var1.readInt();
        **this.d = var1.readInt();**
    }

 public void writeToParcel(Parcel var1, int var2) {
        var1.writeString(this.e);
        var1.writeString(this.f);
        var1.writeString(this.g);
        var1.writeInt(this.h);
        var1.writeInt(this.i);
        var1.writeInt(this.j);
        var1.writeInt(this.k);
    }
```

**Comment by yujiaao** [comment]
`
//Error fix
// (powered by Fernflower decompiler)
//

package com.aprilbrother.aprilbrothersdk;

import android.os.Parcel;
import android.os.Parcelable;
import android.text.TextUtils;

import java.math.BigDecimal;

public class Beacon implements Parcelable {
    public static final Parcelable.Creator<Beacon> CREATOR;

    static {
        CREATOR = new Parcelable.Creator<Beacon>() {

            public final Beacon createFromParcel(final Parcel parcel) {
                return new Beacon(parcel);
            }

            public final Beacon[] newArray(final int n) {
                /*SL:1*/
                return new Beacon[n];
            }
        };
    }

    private final String proximityUUID;
    private final String name;
    private final String macAddress;
    private final int major;
    private final int minor;
    private final int measuredPower;
    private final int rssi;
    protected Integer howFar;
    protected Double b;
    protected Double c;
    int power;

    private Beacon(Parcel parcel) {
        this.c = null;
        this.proximityUUID = parcel.readString();
        this.name = parcel.readString();
        this.macAddress = parcel.readString();
        this.major = parcel.readInt();
        this.minor = parcel.readInt();
        this.measuredPower = parcel.readInt();
        this.rssi = parcel.readInt();
        this.power = parcel.readInt();
    }

    public Beacon(String uuid, String name, String macAddress, int major, int minor, int measuredPower, int rssi) {
        this.c = null;
        this.proximityUUID = Utils.normalizeProximityUUID(uuid);
        if (TextUtils.isEmpty(name)) {
            this.name = "Unknown";
        } else {
            this.name = name;
        }

        this.macAddress = macAddress;
        this.major = major;
        this.minor = minor;
        this.measuredPower = measuredPower;
        this.rssi = rssi;
    }

    public Beacon(String uuid, String var2, String var3, int var4, int var5, int var6, int var7, int var8) {
        this.c = null;
        this.proximityUUID = Utils.normalizeProximityUUID(uuid);
        if (TextUtils.isEmpty(var2)) {
            this.name = "Unknown";
        } else {
            this.name = var2;
        }

        this.macAddress = var3;
        this.major = var4;
        this.minor = var5;
        this.measuredPower = var6;
        this.rssi = var7;
        this.power = var8;
    }

    private static double xishu(int power, double rssi) {
        if (rssi == 0.0D) {
            return -1.0D;
        } else if (power == 0) {
            return -1.0D;
        } else {
            if (rssi > 0.0D) {
                rssi -= 128.0D;
            }

            double var3;
            return (var3 = rssi * 1.0D / (double) power) < 1.0D ? Math.pow(var3, 10.0D) : 0.89976D * Math.pow(var3, 7.7095D) + 0.111D;
        }
    }

    public int describeContents() {
        return 0;
    }

    public boolean equals(Object o) {
        if (this == o) {
            return true;
        } else if (o != null && this.getClass() == o.getClass()) {
            Beacon var2 = (Beacon) o;
            return this.macAddress.equals(var2.macAddress);
        } else {
            return false;
        }
    }

    public double getDistance() {
        if (this.b == null) {
            if (this.rssi > 0) {
                this.b = Double.valueOf(xishu(this.measuredPower, (double) (this.rssi - 128)));
            } else {
                this.b = Double.valueOf(xishu(this.measuredPower, (double) this.rssi));
            }
        }

        return (new BigDecimal(this.b.doubleValue())).setScale(2, 4).doubleValue();
    }

    public String getMacAddress() {
        return this.macAddress;
    }

    public int getMajor() {
        return this.major;
    }

    public int getMeasuredPower() {
        return this.measuredPower;
    }

    public int getMinor() {
        return this.minor;
    }

    public String getName() {
        return this.name;
    }

    public int getProximity() {
        if (this.howFar == null) {
            double var1;
            this.howFar = Integer.valueOf((var1 = this.getDistance()) < 0.0D ? 0 : (var1 >= 0.0D && var1 < 0.5D ? 1 : (var1 >= 0.5D && var1 < 3.0D ? 2 : 3)));
        }

        return this.howFar.intValue();
    }

    public String getProximityUUID() {
        return this.proximityUUID;
    }

    public int getRssi() {
        return this.rssi;
    }

    public int getPower() {
        return this.power;
    }

    public int hashCode() {
        int var1 = this.proximityUUID.hashCode();
        var1 = 31 * var1 + this.major;
        return 31 * var1 + this.minor;
    }

    public String toString() {
        return com.aprilbrother.aprilbrothersdk.internal.a.a(this).a("macAddress", this.macAddress).a("proximityUUID", this.proximityUUID).a("major", this.major).a("minor", this.minor).a("measuredPower", this.measuredPower).a("rssi", this.rssi).toString();
    }

    public void writeToParcel(Parcel parcel, int flags) {
        parcel.writeString(this.proximityUUID);
        parcel.writeString(this.name);
        parcel.writeString(this.macAddress);
        parcel.writeInt(this.major);
        parcel.writeInt(this.minor);
        parcel.writeInt(this.measuredPower);
        parcel.writeInt(this.rssi);
        parcel.writeInt(this.power);
    }
}
`

**Comment by syxdzc** [comment]
Did you use the lastest version 1.6.7 ?
There no Double c in Parcel

**Comment by yujiaao** [comment]
Yes, the error  I found is in the version 1.6.7 beta, I use the Decompilers to fix the error
