### ISSUE TITLE
Can not debug an exception

### ISSUE THREAD

**Issue by temizermerve** [AprilBrother/AprilBeacon-Android-SDK#9]
03-24 18:48:07.292: E/AndroidRuntime(26350): FATAL EXCEPTION: Thread-1392
03-24 18:48:07.292: E/AndroidRuntime(26350): Process: com.merve.beacon, PID: 26350
03-24 18:48:07.292: E/AndroidRuntime(26350): java.lang.NullPointerException
03-24 18:48:07.292: E/AndroidRuntime(26350): 	at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1018)
03-24 18:48:07.292: E/AndroidRuntime(26350): 	at com.aprilbrother.aprilbrothersdk.service.BeaconService$c$1.run(BeaconService.java:435)
03-24 18:48:07.292: E/AndroidRuntime(26350): 	at java.lang.Thread.run(Thread.java:841)

What might the cause be?

Thanks

**Comment by temizermerve** [comment]
also it started to give this exception suddenly for every versions of our project

any idea?

**Comment by syxdzc** [comment]
which version did you use? did you try sdk1.5.3 ?
